name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"
    tags:
      - "*"
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: poetry

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          poetry env use python3
          python3 -V

      - name: Linting (flake8 & mypy)
        run:
          make lint







